In [1]:
import numpy as np
import sympy as sp
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
%matplotlib qt
sp.init_printing(use_unicode=True)

In [2]:
a_1, a_2, a_3, a_3, a_4, a_5, a_6 = sp.symbols('a_1, a_2, a_3, a_3, a_4, a_5, a_6')
x_1, x_2, x_3, x_3, x_4, x_5, x_6 = sp.symbols('x_1, x_2, x_3, x_3, x_4, x_5, x_6')
y_1, y_2, y_3, y_3, y_4, y_5, y_6 = sp.symbols('y_1, y_2, y_3, y_3, y_4, y_5, y_6')
x,   y = sp.symbols('x,y')

In [3]:
eq1 = sp.Matrix([0,0,0,0,0,0])
eq1[0] = a_1+a_2*x_1+a_3*y_1+a_4*x_1**2+a_5*x_1*y_1+a_6*y_1**2
eq1[1] = a_1+a_2*x_2+a_3*y_2+a_4*x_2**2+a_5*x_2*y_2+a_6*y_2**2
eq1[2] = a_1+a_2*x_3+a_3*y_3+a_4*x_3**2+a_5*x_3*y_3+a_6*y_3**2
eq1[3] = a_1+a_2*x_4+a_3*y_4+a_4*x_4**2+a_5*x_4*y_4+a_6*y_4**2
eq1[4] = a_1+a_2*x_5+a_3*y_5+a_4*x_5**2+a_5*x_5*y_5+a_6*y_5**2
eq1[5] = a_1+a_2*x_6+a_3*y_6+a_4*x_6**2+a_5*x_6*y_6+a_6*y_6**2
eq1

⎡                          2                   2⎤
⎢a₁ + a₂⋅x₁ + a₃⋅y₁ + a₄⋅x₁  + a₅⋅x₁⋅y₁ + a₆⋅y₁ ⎥
⎢                                               ⎥
⎢                          2                   2⎥
⎢a₁ + a₂⋅x₂ + a₃⋅y₂ + a₄⋅x₂  + a₅⋅x₂⋅y₂ + a₆⋅y₂ ⎥
⎢                                               ⎥
⎢                          2                   2⎥
⎢a₁ + a₂⋅x₃ + a₃⋅y₃ + a₄⋅x₃  + a₅⋅x₃⋅y₃ + a₆⋅y₃ ⎥
⎢                                               ⎥
⎢                          2                   2⎥
⎢a₁ + a₂⋅x₄ + a₃⋅y₄ + a₄⋅x₄  + a₅⋅x₄⋅y₄ + a₆⋅y₄ ⎥
⎢                                               ⎥
⎢                          2                   2⎥
⎢a₁ + a₂⋅x₅ + a₃⋅y₅ + a₄⋅x₅  + a₅⋅x₅⋅y₅ + a₆⋅y₅ ⎥
⎢                                               ⎥
⎢                          2                   2⎥
⎣a₁ + a₂⋅x₆ + a₃⋅y₆ + a₄⋅x₆  + a₅⋅x₆⋅y₆ + a₆⋅y₆ ⎦

In [4]:
#sol1 = sp.solve(eq1, a_1, a_2, a_3, a_3, a_4, a_5, a_6)
#sol1

In [5]:
#sol1[a_6].simplify()

In [6]:
#ejemplo

#su = {x_1:0, x_2:1, x_3:2, x_4:1.5, x_5:1, x_6:0.5, y_1:0, y_2:0.5, y_3:1, y_4:1.5, y_5:2, y_6:1}
#a = np.array([0] * 6)
#for j,i in enumerate([a_1, a_2, a_3, a_4, a_5, a_6]):
#    print(j,i)
#    a[j] = sol1[i].subs(su).simplify()
    
#a[3]=.25

In [7]:
su = {x_1:0, x_2:1, x_3:2, x_4:1.5, x_5:1, x_6:0.5, y_1:0, y_2:0.5, y_3:1, y_4:1.5, y_5:2, y_6:1}

sol = []

for i in range(6):
    eq2 = eq1.subs(su)
    eq2[i] = eq2[i]-1
    sol.append(sp.solve(eq2, a_1, a_2, a_3, a_3, a_4, a_5, a_6))

sol

In [8]:
sol2 = sp.solve(eq2, a_1, a_2, a_3, a_3, a_4, a_5, a_6)
sol2

In [9]:
b = []

for k in range(6):
    a = np.array([0.0] * 6)
    for j,i in enumerate([a_1, a_2, a_3, a_4, a_5, a_6]):
        a[j] = float(sol[k][i])
    b.append(a)
    
b

[array([ 1.        , -1.        , -1.        ,  0.22222222,  0.44444444,
         0.22222222]),
 array([ 0.        ,  2.66666667, -1.33333333, -0.88888889, -0.44444444,
         0.44444444]),
 array([ 0.        , -0.66666667,  0.33333333,  0.88888889, -0.88888889,
         0.22222222]),
 array([ 0.        ,  0.        ,  0.        , -0.88888889,  2.22222222,
        -0.88888889]),
 array([ 0.        ,  0.33333333, -0.66666667,  0.22222222, -0.88888889,
         0.88888889]),
 array([ 0.        , -1.33333333,  2.66666667,  0.44444444, -0.44444444,
        -0.88888889])]

In [10]:
%matplotlib qt
fig=plt.figure(figsize=(10,10))
ax = fig.gca(projection='3d')
x = [0,1,2,1.5,1,0.5,0]
y = [0,0.5,1,1.5,2,1,0]
z1 = [0]*7

l1_x = np.linspace(0,2,20)
l1_y = np.linspace(0,1,20)

l2_x = np.linspace(2,1,20)
l2_y = np.linspace(1,2,20)

l3_x = np.linspace(1,0,20)
l3_y = np.linspace(2,0,20)

plt.plot(x,y,z1,'ko-')
for i, c in enumerate(['b','r','b:','r:','b--','r--']):
    L1_N_1 = b[i][0]+b[i][1]*l1_x+b[i][2]*l1_y+b[i][3]*l1_x**2+b[i][4]*l1_x*l1_y+b[i][5]*l1_y**2
    L2_N_1 = b[i][0]+b[i][1]*l2_x+b[i][2]*l2_y+b[i][3]*l2_x**2+b[i][4]*l2_x*l2_y+b[i][5]*l2_y**2
    L3_N_1 = b[i][0]+b[i][1]*l3_x+b[i][2]*l3_y+b[i][3]*l3_x**2+b[i][4]*l3_x*l3_y+b[i][5]*l3_y**2


    plt.plot(l1_x,l1_y,L1_N_1,c)
    plt.plot(l2_x,l2_y,L2_N_1,c)
    plt.plot(l3_x,l3_y,L3_N_1,c)

C:\Users\uie70742\AppData\Local\Temp/ipykernel_11004/3185085520.py:3: MatplotlibDeprecationWarning: Calling gca() with keyword arguments was deprecated in Matplotlib 3.4. Starting two minor releases later, gca() will take no keyword arguments. The gca() function should only be used to get the current axes, or if no axes exist, create new axes with default keyword arguments. To create a new axes with non-default arguments, use plt.axes() or plt.subplot().
  ax = fig.gca(projection='3d')
